packages:
  - 'packages/*'
  - '!packages/webui'
  - 'docs'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@karinjs/node-pty'
catalog:
  "@eslint/eslintrc": "^3"
  "@hono/node-server": "^1.19.2"
  "@mastra/core": "^0.16.2"
  "@mastra/deployer": "^0.16.2"
  "@mastra/libsql": "^0.14.0"
  "@mastra/loggers": "^0.10.11"
  "@mastra/mcp": "^0.12.0"
  "@mastra/memory": "^0.15.0"
  "@parcel/watcher": "^2.5.1"
  "@svgr/webpack": "^8.1.0"
  "@tailwindcss/postcss": "^4.1.11"
  "@tailwindcss/vite": "^4.1.13"
  "@tanstack/router-core": "^1.131.36"
  "@vitejs/plugin-react": "^5.0.2"
  "class-variance-authority": "^0.7.1"
  "clipboardy": "^4.0.0"
  "clsx": "^2.1.1"
  "commander": "^14.0.0"
  "comlink": "^4.4.2"
  "cosmiconfig": "^9.0.0"
  "date-fns": "^4.1.0"
  "debug": "^4.4.1"
  "defu": "^6.1.4"
  "diff": "^8.0.2"
  "dotenv": "^17.2.2"
  "eslint": "^9.31.0"
  "eslint-config-next": "15.4.4"
  "execa": "^9.6.0"
  "glob": "^11.0.3"
  "globby": "^14.1.0"
  "gray-matter": "^4.0.3"
  "hono": "^4.9.6"
  "hono-mcp-server-sse-transport": "^0.0.7"
  "idb-keyval": "^6.2.2"
  "import-meta-ponyfill": "^3.3.1"
  "json5": "^2.2.3"
  "marked": "^16.2.1"
  "mastra": "^0.12.2"
  "mdast-util-from-markdown": "^2.0.2"
  "micromatch": "^4.0.8"
  "minimatch": "^10.0.3"
  "motion": "^12.23.12"
  "ms": "^2.1.3"
  "msw": "^2.11.1"
  "next": "15.4.4"
  "node-pty": "npm:@karinjs/node-pty@^1.1.3"
  "playwright": "^1.55.0"
  "prettier": "^3.6.2"
  "proper-lockfile": "^4.1.2"
  "semver": "^7.7.2"
  "signal-polyfill": "^0.2.2"
  "signal-utils": "^0.21.1"
  "simple-git": "^3.28.0"
  "strip-ansi": "^7.1.2"
  "superjson": "^2.2.2"
  "tailwind-merge": "^3.3.1"
  "tailwind-scrollbar": "^4.0.2"
  "tailwindcss": "^4.1.13"
  "ts-pattern": "^5.8.0"
  "tslib": "^2.8.1"
  "tsx": "^4.20.5"
  "tw-animate-css": "^1.3.8"
  "unist-util-visit": "^5.0.0"
  "uuid": "^13.0.0"
  "vite": "^7.1.5"
  "vite-plugin-web-extension": "^4.4.5"
  "vitest": "^3.2.4"
  "ws": "^8.18.3"
  "yargs": "^18.0.0"
  "yargs-parser": "^22.0.0"
  "zod": "^4.1.5"
  "zod-to-json-schema": "^3.24.6"

catalogs:
  ui:
    "@assistant-ui/react": "^0.10.29"
    "@assistant-ui/react-ai-sdk": "^0.10.16"
    "@assistant-ui/react-markdown": "^0.10.6"
    "@hookform/resolvers": "^5.2.1"
    "@radix-ui/react-accordion": "^1.2.12"
    "@radix-ui/react-alert-dialog": "^1.1.15"
    "@radix-ui/react-dialog": "^1.1.15"
    "@radix-ui/react-label": "^2.1.7"
    "@radix-ui/react-select": "^2.2.6"
    "@radix-ui/react-separator": "^1.1.7"
    "@radix-ui/react-slot": "^1.2.3"
    "@radix-ui/react-switch": "^1.2.6"
    "@radix-ui/react-tabs": "^1.1.13"
    "@radix-ui/react-tooltip": "^1.2.8"
    "@uidotdev/usehooks": "^2.4.1"
    "lucide-react": "^0.543.0"
    "react": "^19.1.1"
    "react-dom": "^19.1.1"
    "react-error-boundary": "^6.0.0"
    "react-hook-form": "^7.62.0"
    "remark-gfm": "^4.0.1"
  types:
    "@types/chrome": "^0.1.9"
    "@types/debug": "^4.1.12"
    "@types/diff": "^8.0.0"
    "@types/json-schema": "^7.0.15"
    "@types/mdast": "^4.0.4"
    "@types/micromatch": "^4.0.9"
    "@types/minimatch": "^5.1.2"
    "@types/ms": "^2.1.0"
    "@types/node": "^24.1.0"
    "@types/proper-lockfile": "^4.1.4"
    "@types/react": "^19.1.12"
    "@types/react-dom": "^19.1.9"
    "@types/semver": "^7.7.1"
    "@types/trusted-types": "^2.0.7"
    "@types/unist": "^3.0.3"
    "@types/wicg-file-system-access": "^2023.10.6"
    "@types/ws": "^8.18.1"
    "@types/yargs": "^17.0.33"
    "@types/yargs-parser": "^21.0.3"
  ai:
    "@ai-sdk/anthropic": "alpha"
    "@ai-sdk/deepinfra": "alpha"
    "@ai-sdk/deepseek": "alpha"
    "@ai-sdk/google": "alpha"
    "@ai-sdk/openai": "alpha"
    "@ai-sdk/provider": "alpha"
    "@ai-sdk/xai": "alpha"
    "@modelcontextprotocol/sdk": "^1.17.5"
    "ai": "^5.0.41"
  gaubee:
    "@gaubee/node": "^0.4.0"
    "@gaubee/nodekit": "^0.12.0"
    "@gaubee/util": "^0.35.1"
  jsr:
    "@std/cli": "jsr:^1.0.20"
